### ISSUE TITLE
node_package: Can't use url based packages

### ISSUE THREAD

**Issue by donaldguy** [poise/poise-javascript#3] opened 2016-06-10 04:41 UTC
`npm install` supports many formats for its package input beyond a simple package name. Notably:
1. `a/b` form github identifiers
2. urls to git repos (including support for specifying a branch as an anchor i.e. `#branch`).

Currently when trying to use such an identifier (`package_name`) `node_package` fails at the shell out to `npm show` intended to infer versioning information. I would imagine that in most cases where a user wishes to point to a git repo, version number per se is irrelevant and can be safely branched around (or a commit sha could be used)

The `nodejs` cookbook on supermarket does support such packages, though it defines a separate `url` attribute on its `nodejs_npm` resource to do so: https://github.com/redguide/nodejs#nodejs_npm

I tried to workaround this using a `git` resource to check out and then `npm_install` on that working copy, however, it is not clear how to do this for the `--global` scope (such that the forked package in question can be used as a cli tool)

fails as

```
ERROR: node_package[git://github.com/benweissmann/spacejam.git#refactor] had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of ["/opt/nodejs-4.2.0/bin/node", "/opt/nodejs-4.2.0/bin/npm", "show", "--json", "--global", "git://github.com/benweissmann/spacejam.git#refactor"] ----
STDOUT:
STDERR: npm ERR! Linux 3.13.0-87-generic
npm ERR! argv "/opt/nodejs-4.2.0/bin/node" "/opt/nodejs-4.2.0/bin/npm" "show" "--json" "--global" "git://github.com/benweissmann/spacejam.git#refactor"
npm ERR! node v4.2.0
npm ERR! npm  v3.9.5

npm ERR! Cannot use view command in global mode.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
---- End output of ["/opt/nodejs-4.2.0/bin/node", "/opt/nodejs-4.2.0/bin/npm", "show", "--json", "--global", "git://github.com/benweissmann/spacejam.git#refactor"] ----
```

**Comment by coderanger** [comment] 2016-06-10 04:52
The problem is most of these cases are non-idempotent (this comes up with `pip` too). In general it's probably better to use a `javascript_execute` resource so you can define your own `not_if`/`only_if` guards based on the specifics.

**Comment by coderanger** [comment] 2016-07-19 10:09
Closing this out, if `javascript_execute` doesn't work, please let me know.

**Closed as completed by coderanger** 2016-07-19 10:09 UTC
